### PR TITLE
Support python 3

### PR DESCRIPTION
**Pull request by toshetah**

### CODE REVIEW

**Comment by toshetah** [comment]
Hey,

I've solved it for the bounty, but I can't link the PR into the bounty. If you accept please consider me as the hunter. :)

THanks!

**Comment by ericfitz** [comment]
Hey toshetah, I tried your branch but I'm still getting errors that look like python2 syntax:

```
┌─(~/Projects/bounty)───────────────────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:01:04-0400)──> git clone git@github.com:toshetah/chainbreaker.git                                        ──(Sun 2022-04-03)─┘
Cloning into 'chainbreaker'...
The authenticity of host 'github.com (140.82.113.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 157 (delta 17), reused 13 (delta 11), pack-reused 117
Receiving objects: 100% (157/157), 124.12 KiB | 1.01 MiB/s, done.
Resolving deltas: 100% (83/83), done.
┌─(~/Projects/bounty)───────────────────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:01:14-0400)──> ls                                                                                        ──(Sun 2022-04-03)─┘
chainbreaker
┌─(~/Projects/bounty)───────────────────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:01:24-0400)──> cd chainbreaker                                                                           ──(Sun 2022-04-03)─┘
┌─(~/Projects/bounty/chainbreaker)──────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:01:26-0400 on master)──> ls                                                                              ──(Sun 2022-04-03)─┘
LICENSE         README.md       chainbreaker.py pbkdf2.py       pyDes.py        schema.py
┌─(~/Projects/bounty/chainbreaker)──────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:01:27-0400 on master)──> sudo python3 ./chainbreaker.py -p -o ~/Downloads/keychain-export/ --export-private-keys /Library/Keychains/System.keychain --unlock-file /var/db/SystemKey
  File "/Users/eric/Projects/bounty/chainbreaker/./chainbreaker.py", line 153
    print "private_key_offset", self._get_private_key_record(private_key_offset)
          ^
SyntaxError: invalid syntax
```

**Comment by ericfitz** [comment]
@toshetah - I'm still getting type errors:

```
┌─(~/Projects/bounty)───────────────────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:05:52-0400)──> git clone -b Support-python-3 git@github.com:toshetah/chainbreaker.git                    ──(Sun 2022-04-03)─┘
Cloning into 'chainbreaker'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 157 (delta 17), reused 13 (delta 11), pack-reused 117
Receiving objects: 100% (157/157), 121.70 KiB | 1.52 MiB/s, done.
Resolving deltas: 100% (83/83), done.
┌─(~/Projects/bounty)───────────────────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:06:19-0400)──> cd chainbreaker                                                                           ──(Sun 2022-04-03)─┘
┌─(~/Projects/bounty/chainbreaker)──────────────────────────────────────────────────────────────────────(eric@Erics-Mac-Pro:s000)─┐
└─(12:06:26-0400 on Support-python-3)──> sudo python3 ./chainbreaker.py -p -o ~/Downloads/keychain-export/ --export-private-keys /Library/Keychains/System.keychain --unlock-file /var/db/SystemKey
Unlock Password:
2022-04-03 12:06:39,337 - INFO -

ChainBreaker 2 - https://github.com/gaddie-3/chainbreaker

2022-04-03 12:06:39,337 - INFO - Runtime Command: ./chainbreaker.py -p -o /Users/eric/Downloads/keychain-export/ --export-private-keys /Library/Keychains/System.keychain --unlock-file /var/db/SystemKey
2022-04-03 12:06:39,337 - INFO - Keychain: /Library/Keychains/System.keychain
2022-04-03 12:06:39,337 - INFO - Keychain MD5: dcbe47b235cf7fbe6d478b908f2db39e
2022-04-03 12:06:39,337 - INFO - Keychain 256: fb2b63894837680590f21b8ade98340b2a2f283e20324d963fcab49c794bf16d
2022-04-03 12:06:39,338 - INFO - Dump Start: 2022-04-03 12:06:39.337130
2022-04-03 12:06:39,339 - WARNING - Keychain signature does not match. are you sure this is a valid keychain file?
Traceback (most recent call last):
  File "/Users/eric/Projects/bounty/chainbreaker/./chainbreaker.py", line 1290, in <module>
    keychain = Chainbreaker(args.keychain, unlock_password=args.password, unlock_key=args.key,
  File "/Users/eric/Projects/bounty/chainbreaker/./chainbreaker.py", line 77, in __init__
    self.unlock_password = unlock_password
  File "/Users/eric/Projects/bounty/chainbreaker/./chainbreaker.py", line 584, in unlock_password
    master_key = self._generate_master_key(self._unlock_password)
  File "/Users/eric/Projects/bounty/chainbreaker/./chainbreaker.py", line 348, in _generate_master_key
    return str(PBKDF2(pw, str(bytearray(self.dbblob.Salt)), 1000, Chainbreaker.KEYLEN))
  File "/Users/eric/Projects/bounty/chainbreaker/pbkdf2.py", line 39, in __init__
    for i in range(1, l + 1):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by toshetah** [comment]
Sorry @ericfitz ! I committed a fix.

**Comment by GingerGeneste** [comment]
I have created a PR for this a while ago, see: https://github.com/n0fate/chainbreaker/pull/21

**Pull request closed without merging**
