### PR TITLE
Handle multiple key candidates, print undumped data, refactor code

### PR DESCRIPTION
**Pull request by gquere**
Hello,

Hope this can help your projet!

Modifications:
* an option to handle multiple key candidates by chaining -k arguments, i.e. "-k abcd -k efgh -k ijkl" and trying each of them until one successfully decrypts the keychain
* re-enabled printing of data which are not dumped to disk, otherwise those are missed by users
* a lot of refactoring to improve readability of the script

Although I successfully tested on the few keychains I had, I might have broken a few things. You should consider adding unit/functional tests.

### CODE REVIEW

**Comment by getaaron** [comment]
Thanks for the PR

**Comment by gquere** [comment]
> Should we delete all the commented hexdumps?
Might be sometimes useful to print hex data, although here the hexdump dependency is useless IMO and breaks things on my debian based system (no such import exists and there is no package named as such although I haven't searched more).

A simple
`''.join('{:02x}'.format(data_byte)` for data_byte in data)`
would surely do the trick.

**Comment by n0fate** [comment]
I will change a code for printing result soon.

**Comment by gquere** [comment]
Hello,

Any plans to merge? I can change the PR a bit if there are missing things

**Pull request merged**
